name: Cloudops sample deployment

on:
  workflow_dispatch:
  push:
    branches: [main]
  #  paths: ["infra/**"]

  pull_request:
    branches: [main]
  #  paths: ["infra/**"]

env:
  appname: webapp
  region: ap-southeast-2
  agent: ubuntu-20.04
  devfiletf: devtest.tfvars
  s3deploybucket: kepungcodeartifact
  webappArtifact: deployment.zip
  devtestEnvironment: dev
  uatEnvironment: uat
  prodEnvironment: prod
  
jobs:
  # tfplan:
  #   uses: ./.github/workflows/terraform.yaml
  #   with:
  #     tffile: devtest.tfvars
  #     region: ap-southeast-2
  #   secrets:
  #      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
  #      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  appdeploy:
    #needs: [tfplan]
    name: Web Deployment dev
    uses: ./.github/workflows/webdeploy.yaml
    with:
      appname: app1
      region: ap-southeast-2
      s3deploybucket: kepungcodeartifact
      webappArtifact: deployment.zip
      env: app1-dev

    secrets:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
