name: Cloudops sample deployment

on:
  workflow_dispatch:
  push:
    branches: [main]
  #  paths: ["infra/**"]

  pull_request:
    branches: [main]
  #  paths: ["infra/**"]

env:
  region: ap-southeast-2
  agent: ubuntu-20.04

jobs:
  plan:
    name: Terraform plan
    runs-on: ${{ env.agent }}

    steps:
      - uses: ${{ env.agent }}
   
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $region

      - name: Initialise project and view terraform plan
        run: |
          cd infra 
          terraform fmt
          terraform init 
          terraform plan -var='example_api_key=${{ secrets.EXAMPLE_API_KEY }}'

  # deploy:
  #     name: Terraform Deploy
  #     needs: plan
  #     if: github.ref == 'refs/heads/main'
  #     runs-on: $agent

  #     steps:
  #       - uses: actions/checkout@v3

  #       # - name: Use Node.js 14.x
  #       #   uses: actions/setup-node@v1
  #       #   with:
  #       #     node-version: 14.x

  #       - name: Configure AWS credentials
  #         uses: aws-actions/configure-aws-credentials@v2
  #         with:
  #           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #           aws-region: $region
            
  #       - name: Initialise project and deploy terraform
  #         run: |
  #           cd terraform
  #           cd qa
  #           terraform fmt
  #           terraform init
  #           terraform apply -var='example_api_key=${{ secrets.EXAMPLE_API_KEY }}' --auto-approve=true