name: Cloudops sample deployment

on:
  workflow_dispatch:
  push:
    branches: [main]
  #  paths: ["infra/**"]

  pull_request:
    branches: [main]
  #  paths: ["infra/**"]

env:
  appname: webapp
  region: ap-southeast-2
  agent: ubuntu-20.04
  devfiletf: 'devtest.tfvars'
  s3deploybucket: 'kepungcodeartifact'

jobs:
  tfplan:
    name: Terraform plan
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: zip web deployment
        run: |
          zip -r deployment.zip ./dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.region }}

      - name: Upload to S3
        uses: aws-actions/amazon-s3-upload@v1
        with:
          bucket: kepungcodeartifact
          key: deployment.zip

      - name: Create Elastic Beanstalk Application Version
        uses: aws-actions/create-elastic-beanstalk-application-version@v1
        with:
          application-name: my-app  # Replace with your application name
          version-label: ${{ github.sha }}
          source-bundle: s3://my-elasticbeanstalk-app/deployment.zip
          
      - name: Initialise project and view terraform plan
        run: |
          cd infra
          terraform fmt
          terraform init 
          terraform plan --var-file='${{ env.devfiletf }}'

  appdeploy:
    needs: [tfplan]
    name: Web Deployment dev
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3

      - name: zip web deployment
        run: |
          zip -r deployment.zip ./dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.region }}

      - name: Upload to S3
        uses: aws-actions/amazon-s3-upload@v1
        with:
          bucket: ${{ env.s3deploybucket }}
          key: deployment.zip

      - name: Create Elastic Beanstalk Application Version
        uses: aws-actions/create-elastic-beanstalk-application-version@v1
        with:
          application-name: ${{ env.appname }}
          version-label: ${{ github.sha }}
          source-bundle: s3://${{ env.s3deploybucket}}/deployment.zip
          
     
  # deploy:
  #     name: Terraform Deploy
  #     needs: plan
  #     if: github.ref == 'refs/heads/main'
  #     runs-on: $agent

  #     steps:
  #       - uses: actions/checkout@v3

  #       # - name: Use Node.js 14.x
  #       #   uses: actions/setup-node@v1
  #       #   with:
  #       #     node-version: 14.x

  #       - name: Configure AWS credentials
  #         uses: aws-actions/configure-aws-credentials@v2
  #         with:
  #           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #           aws-region: $region
            
  #       - name: Initialise project and deploy terraform
  #         run: |
  #           cd terraform
  #           cd qa
  #           terraform fmt
  #           terraform init
  #           terraform apply -var='example_api_key=${{ secrets.EXAMPLE_API_KEY }}' --auto-approve=true