on:
  workflow_call:
    inputs:
      tffile: 
          required: true
          type: string
      region:
        required: true
        type: string 

    secrets: 
       AWS_ACCESS_KEY_ID: 
          required: true
       AWS_SECRET_ACCESS_KEY: 
          required: true

jobs:
  tfplan:
    name: Terraform plan
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
          
      - name: Initialise project and view terraform plan
        run: |
          cd infra
          terraform fmt
          terraform init 
          terraform plan --var-file='${{ inputs.tffile }}'
 
  deploy:
      name: Terraform Deploy
      needs: tfplan
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ inputs.region }}
            
        - name: Initialise project and deploy terraform
          run: |
            echo 'deploying terraform'
            # cd terraform
            # cd qa
            # terraform fmt
            # terraform init
            # terraform apply --var-file='${{ inputs.tffile }}' --auto-approve=true